const MONTHS = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
]

const getDaysInMonth = (date) => new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate()

// Only edit below

/**
 * Generates an array of objects representing the weeks and days in a month.
 * It initializes a date object to the current date with the day set to 1.
 * startDay: The day of the week on which the month starts.
 * daysInMonth: The total number of days in the month.
 * Uses nested loops to populate array - result
 * @returns {*[]}
 */
const createData = () => {
    const current = new Date()
    current.setDate(1)

    const startDay = current.getDay()
    const daysInMonth = getDaysInMonth(current)

    const weeks = Math.ceil((startDay + daysInMonth) / 7)
    const days = 7
    const result = []

    for (let weekIndex = 0; weekIndex < weeks; weekIndex++) {
    result.push({
        week: weekIndex + 1,
        days: []
    })

    for (let dayIndex = 0; dayIndex < days; dayIndex++) {
        const day = weekIndex * days + dayIndex - startDay + 1;
        const isValid = day > 0 && day <= daysInMonth

        result[weekIndex].days.push({
            dayOfWeek: dayIndex + 1,
            value: isValid ? day : '',
        })
    }
}
return result;
};

/**
 * takes three parameters
 * @param existing HTML string
 * @param classString string representing css classes
 * @param value content of table cell
 * @returns {string}
 */
const addCell = (existing, classString, value) => {
    const result = /* html */ `
        ${existing}

        <td class="${classString}">
            ${value}
        </td>
    `
    return result
}

/**
 * Data generated by createData, convert it into an HTML string for rendering.
 * It iterates over each week and days, creating table cells for each day.
 * Applies different CSS classes based on whether the day is today, a weekend day, or part of an alternate week.
 * @param data
 * @returns {string}
 */
const createHtml = (data) => {
    let result = '';

    for (const { week, days } of data ) {
        let inner = "";
        inner = addCell(inner, 'table__cell table__cell_sidebar', `Week ${week}`);

    for (const { dayOfWeek, value } of days) {
            const isToday = new Date().getDate() === value
            const isWeekend = dayOfWeek === 1 || dayOfWeek === 7;
            const isAlternate = week % 2 === 0;

            let classString = 'table__cell'

            if (isToday) classString = `${classString} table__cell_today`
            if (isWeekend) classString = `${classString} table__cell_weekend`
            if (isAlternate) classString = `${classString} table__cell_alternate`
            inner = addCell(inner, classString, value)
        }

        result = `
            ${result}
            <tr>${inner}</tr>
        `
    }
    return result
}

// Only edit above

const current = new Date()
document.querySelector('[data-title]').innerText = `${MONTHS[current.getMonth()]} ${current.getFullYear()}`

const data = createData()
document.querySelector('[data-content]').innerHTML = createHtml(data)